[package]
name = "generate-ast"
version = "0.1.0"
description = "Dissecting Rust Traits to Learn Their Secrets"

[[bin]]
name = "generate-ast"
path = "src/main.rs"


[dependencies]
rlox = { path = ".." }